### ISSUE TITLE
Why is the following code unable to compile under Arduino nano. 

### ISSUE THREAD

**Issue by rebelboy** [okalachev/mavlink-arduino#1]
there is not enough memory。  

```cpp
#include "mavlink/mavlink.h"

void setup() {
  Serial.begin(57600);
}

void loop() {

Mavlink_Receive();

}

void Mavlink_Receive()
{
  mavlink_message_t msg;
  mavlink_status_t  status;


  while ( Serial.available() > 0 )
  {
    uint8_t c = Serial.read();

    if ( mavlink_parse_char( MAVLINK_COMM_0, c, &msg, &status ) )
    {


      switch ( msg.msgid )
      {
        
      }
    }
    
  }
}
```

**Comment by okalachev** [comment]
Hi, @rebelboy! At first, you should not use `#include "mavlink/mavlink.h"` if you're using this library, but use just `#include <MAVLink.h>` instead. See the examples in [examples](https://github.com/okalachev/mavlink-arduino/tree/master/examples) directory.

Second, seems that modern MAVLink library uses too much memory just to initialize the parser to be run on Arduino Nano. You can reduce the memory usage by reducing the number of parser channels this way:

```cpp
#define MAVLINK_COMM_NUM_BUFFERS 1
#include <MAVLink.h>
```

But even with this it requires 2959 bytes of RAM (Arduino Nano has only 2048).

I can research a bit more, if it possible to reduce the RAM usage in MAVLink library more, but I guess it's impossible to run it on Nano anyway. I recommend you using board with more memory, like ESP boards.

**Comment by rebelboy** [comment]
> Hi, @rebelboy! At first, you should not use `#include "mavlink/mavlink.h"` if you're using this library, but use just `#include <MAVLink.h>` instead. See the examples in [examples](https://github.com/okalachev/mavlink-arduino/tree/master/examples) directory.
> 
> Second, seems that modern MAVLink library uses too much memory just to initialize the parser to be run on Arduino Nano. You can reduce the memory usage by reducing the number of parser channels this way:
> 
> ```c++
> #define MAVLINK_COMM_NUM_BUFFERS 1
> #include <MAVLink.h>
> ```
> 
> But even with this it requires 2959 bytes of RAM (Arduino Nano has only 2048).
> 
> I can research a bit more, if it possible to reduce the RAM usage in MAVLink library more, but I guess it's impossible to run it on Nano anyway. I recommend you using board with more memory, like ESP boards.


Thank you very much for your answer.

I just need to read the MAVLINK-MSG-ID_GPSRAW-INT message in Mavlink v2.

I want to pass on this message to my AAT.

**Comment by okalachev** [comment]
It doesn't matter, if you want to parse only one message or all of them, MAVLink just uses a lot of memory to initialize the parser itself. You can reduce the memory usage by not using `mavlink_status_t  status` and passing `NULL` instead of it, but still it doesn't fit to Arduino Nano's RAM.

You should use a board with more RAM for this task, out of [this list](https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems). I recommend ESP32, which is even cheaper than Arduino Nano.

**Comment by rebelboy** [comment]
> It doesn't matter, if you want to parse only one message or all of them, MAVLink just uses a lot of memory to initialize the parser itself. You can reduce the memory usage but not using `mavlink_status_t status` and passing `NULL` instead of it, but still it doesn't fit to Arduino Nano's RAM.
> 
> You should use a board with more RAM for this task, out of [this list](https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems). I recommend ESP32, which is even cheaper than Arduino Nano.

I take your advice. Change to ESP.
I really appreciate your help
