### ISSUE TITLE
Compile Errors in Convenience Functions

### ISSUE THREAD

**Issue by RbtsEvrwhr-Riley** [okalachev/mavlink-arduino#2]
Hello,

I was trying to test out an implementation of mavlink ftp using your "example" here https://github.com/okalachev/Firmware/blob/0d0fcb140ce59ddc6ab50fef177534e544ce31a4/src/modules/mavlink/mavlink_ftp.cpp

This calls mavlink_msg_file_transfer_protocol_send_struct which requires mavlink.h to be compiled with #define MAVLINK_USE_CONVENIENCE_FUNCTIONS

Now I know this is a bit out in the weeds doing it on Arduino, but I noticed even with nothing to do with the mavlink_ftp_code, if this flag is set, the library fails to compile with a number of errors:

`In file included from C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.h:49,
                 from D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:62:
C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.hpp:72:4: warning: #warning Using ESP32-based board [-Wcpp]
   #warning Using ESP32-based board
    ^~~~~~~
D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:63: warning: "TIMER_INTERRUPT_DEBUG" redefined
 #define TIMER_INTERRUPT_DEBUG       0 // redefine for ESP32FastTimerInterrupt
 
In file included from C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.hpp:107,
                 from C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.h:49,
                 from D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:62:
C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo_Debug.h:50: note: this is the location of the previous definition
   #define TIMER_INTERRUPT_DEBUG         1
 
D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:64: warning: "ISR_SERVO_DEBUG" redefined
 #define ISR_SERVO_DEBUG             0
 
In file included from C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.hpp:107,
                 from C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo.h:49,
                 from D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:62:
C:\Users\overc\Documents\Arduino\libraries\ESP32_New_ISR_Servo\src/ESP32_New_ISR_Servo_Debug.h:54: note: this is the location of the previous definition
   #define ISR_SERVO_DEBUG               1
 
D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:13:16: warning: 'use_servos_for_movement' initialized and declared 'extern'
 extern boolean use_servos_for_movement = false;  // if not, use 2p motors. 4p motors is deprecated. this does, and ever should, only affect the Motors(...) function. start with motors because it's safe
                ^~~~~~~~~~~~~~~~~~~~~~~
D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:41:16: warning: 'network_has_failed' initialized and declared 'extern'
 extern boolean network_has_failed = false;
                ^~~~~~~~~~~~~~~~~~
In file included from c:\users\overc\documents\arduino\libraries\mavlink\mavlink\protocol.h:77,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/mavlink/common/common.h:29,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/mavlink/common/mavlink.h:32,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/MAVLink.h:6,
                 from D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:45:
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h: In function 'void _mav_finalize_message_chan_send(mavlink_channel_t, uint32_t, const char*, uint8_t, uint8_t, uint8_t)':
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h:344:22: error: 'mavlink_system' was not declared in this scope
             buf[3] = mavlink_system.sysid;
                      ^~~~~~~~~~~~~~
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h:344:22: note: suggested alternative: 'mavlink_system_t'
             buf[3] = mavlink_system.sysid;
                      ^~~~~~~~~~~~~~
                      mavlink_system_t
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h:358:22: error: 'mavlink_system' was not declared in this scope
             buf[5] = mavlink_system.sysid;
                      ^~~~~~~~~~~~~~
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h:358:22: note: suggested alternative: 'mavlink_system_t'
             buf[5] = mavlink_system.sysid;
                      ^~~~~~~~~~~~~~
                      mavlink_system_t
In file included from c:\users\overc\documents\arduino\libraries\mavlink\mavlink\protocol.h:77,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/mavlink/common/common.h:29,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/mavlink/common/mavlink.h:32,
                 from C:\Users\overc\Documents\Arduino\libraries\MAVLink/MAVLink.h:6,
                 from D:\robotseverywhere\smol\smolrover\smolrover_servos_and_2p_motors\smolrover_servos_and_2p_motors.ino:45:
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h: In function 'void _mavlink_send_uart(mavlink_channel_t, const char*, uint16_t)':
c:\users\overc\documents\arduino\libraries\mavlink\mavlink\mavlink_helpers.h:1146:3: error: 'comm_send_ch' was not declared in this scope
   comm_send_ch(chan, (uint8_t)buf[i]);
   ^~~~~~~~~~~~
`

This is being compiled on AI_THINKER_ESP32CAM, and everything has been working (and driving!) without the convenience functions flag enabled. We are quite impressed with your work on this lib.

**Comment by okalachev** [comment]
Hi!

>I was trying to test out an implementation of mavlink ftp using your "example" here https://github.com/okalachev/Firmware/blob/0d0fcb140ce59ddc6ab50fef177534e544ce31a4/src/modules/mavlink/mavlink_ftp.cpp

This is not an example for this library, this is code from PX4 flight controller, which uses regular MAVLink (my library is only a convenient wrapper for installation using Arduino).

>Now I know this is a bit out in the weeds doing it on Arduino, but I noticed even with nothing to do with the mavlink_ftp_code, if this flag is set, the library fails to compile with a number of errors:

Your error includes a lot of references to your code, which I don't have access to, so I cannot understand the issue.

Please, provide an input Arduino code you want to compile (preferably the minimal example which causes your issue), and error you get. Then I can understand and investigate the problem.

>We are quite impressed with your work on this lib.

Thanks!

**Comment by okalachev** [comment]
@RbtsEvrwhr-Riley

**Comment by okalachev** [comment]
Sorry, I need your clarification to work on the issue. If you're able to provide that, feel free to reopen the issue.
